requirements.txt, wellregistry/wellregistry/settings.py
Title
-----------
Description
-----------
=> support CIDR ranges

buildJenkinsfile, deployJenkinsfile
Title
-----------
Description
-----------
=> Updated Jenkins files to latest pipeline and to use the team:iow agent.

Dockerfile, Makefile
Title
-----------
Description
-----------
=> re-add migrations and include dependency shared libraries

requirements.txt, wellregistry/wellregistry/urls.py
We are trying to fix a url mapping issue on the deployed docker container. This fix does work locally.
=> Map the root of all urls to 'registry/'

.gitignore, CHANGELOG.md, Dockerfile, Makefile, requirements.txt, wellregistry/.env.sample, wellregistry/wellregistry/settings.py
Description
-----------
Added whitenoise as a python dependency. This will be used to serve the static through the gunicorn server.
=> Ngwmn 1996 - Admin static is not being served when application is deployed to labs-dev.wma.chs.usgs.gov	

wellregistry/wellregistry/settings.py
Title
-----------
Description
-----------
=> Change static url to start at /registry/

wellregistry/registry/migrations/0008_populate_lookups.py, wellregistry/registry/migrations/initial_data/county.csv, wellregistry/registry/migrations/initial_data/state.csv
Title
-----------
Description
-----------
=> Adjust lookups

wellregistry/registry/management/commands/initial_data/agency.csv
- [ x] Make sure all tests run
- [x ] Update the changelog appropriately
add new agencies
-----------
add new agencies as specified in NGWMN-1760
Description
-----------
=> add new agencies, NGWMN-1760

oracleToPostgresSitesETL
- [ na] Make sure all tests run
- [na ] Update the changelog appropriately
Title
-----------
NGWMN-1760.  Created a manual process to export a csv from the Oracle sites table and pull it into Postgres.  Then wrote reusable sql code to insert the data into the registry.registry_monitoring location table.
Description
-----------
=> Oracle to Postgres sites ETL directions and sql code, NGWMN-1760

wellregistry/registry/management/commands/initial_data/agency.csv
- [NA ] Make sure all tests run
- [NA ] Update the changelog appropriately
Title
-----------
Add SJRWMD (NGWMN-2032) and UKKGS (NGWMN-2033) to new agency table
Description
-----------
=> add UKKGS and SJRWMD to agency list

CHANGELOG.md, wellregistry/registry/tests/test_views.py, wellregistry/wellregistry/settings.py
Title
-----------
Description
-----------
=> Ngwmn 2035 - Added pagination

wellregistry/registry/views.py
Title
-----------
Description
-----------
=> Select related to queryset

wellregistry/wellregistry/settings.py
Title
-----------
Description
-----------
=> Add configuration parameter to set ssl_header

CHANGELOG.md, wellregistry/registry/serializers.py
=> Ngwmn 2035 - Updated the REST endpoint to use full UnitsLookup

CHANGELOG.md, wellregistry/registry/admin/fetch_from_nwis.py, wellregistry/registry/management/commands/initial_data/lcl_aqfr.csv, wellregistry/registry/tests/admin/test_fetch_from_nwis.py, wellregistry/registry/tests/fake_data.py, wellregistry/wellregistry/__init__.py
The following fields also need to be populated from the NWIS site service call:
Altitude Units - defaulted to ft
Well Depth Units - defaulted to ft
Local Aquifer Name - Created Screen Scrape to pull Local Aquifer Data to CSV file
Created function to get  Local_Auqifer_Name by State_Cd and Aqfr_Cd
=> Well_Depths_Unit, Altitude_Units, Local_Aquifer_Name

wellregistry/registry/admin/fetch_from_nwis.py, wellregistry/registry/models.py
Users will be unable to submit a new site if no well depth information is entered
This is a requirement for all users (both external and USGS)
*set to required
=> well_depth required

Dockerfile, README.md, wellregistry/registry/__init__.py, wellregistry/registry/admin/fetch_from_nwis.py, wellregistry/wellregistry/__init__.py
Title
-----------
Fix application to run in Docker
Description
-----------
We originally put the code to initialize the lookups in the project directory (wellregistry/__init__.py). This failed when running within the docker container using gunicorn because the settings are not yet initialized when this module is executed. Moved the code to the registry application directory (registry/__init__.py) to fix this issue.
=> Fix docker build

Dockerfile
Title
-----------
Description
-----------
=> Jenkins doesn't like installing npm. Taking it out.

CHANGELOG.md, wellregistry/wellregistry/templates/registration/login.html
=> Ngwmn 2023

CHANGELOG.md, wellregistry/registry/admin/monitoring_location.py
- [ x] Update the changelog appropriately
Title
-----------
Tooltips on all fields
Description
-----------
added tooltips on all fields in add/edit monitoring_location
=> Ngwmn 2043

Dockerfile
Title
-----------
Description
-----------
=> turning on gunicorn debug level logging.

Dockerfile
Title
-----------
Description
-----------
=> Increasing the timeout in gunicorn

Dockerfile
Title
-----------
Description
-----------
=> Removed log-level and timeout from gunicorn commands.

.bumpversion.cfg, CHANGELOG.md, code.json, wellregistry/wellregistry/__init__.py
I truncated the CHANGELOG for this first official release to better indicated what is in the release without going into detail that isn't very meaningful.
=> Release 1105

CHANGELOG.md, wellregistry/wellregistry/static/css/admin.css
=> Ngwmn 2042 - Fix delete button at bottom of site list that is truncated

.vscode/settings.json, CHANGELOG.md, wellregistry/wellregistry/static/css/admin.css, wellregistry/wellregistry/templates/admin/submit_line.html
- [ x] Make sure all tests run
Title
-----------
Add "cancel" or "back" button to site page
Description
-----------
When users are adding or editing a site, there is no obvious way for them to exit without saving or go back to the site list. Users need a way to abort an edit.
 
This is more of a 'cancel' button. For canceling out of the current editing session.
=> Ngwmn 2041

CHANGELOG.md, wellregistry/registry/models.py
Title
-----------
Change text in Well Registry application to read "water-level" and "water quality"
Description
-----------
As a new user to the NGWMN, I want to see "water levels" and "water quality" rather than WL and QW, so that I don't have to learn a USGS-ism to know what boxes to check
=> Change text in edit screens to read "water-level" and "water quality"

CHANGELOG.md, wellregistry/wellregistry/templates/admin/bulk_upload.html
Title
-----------
added instruction line  for bulk upload
Description
-----------
On bulk upload page, add instruction line that only .csv files can be submitted
=> added instruction line  for bulk upload

CHANGELOG.md, wellregistry/registry/tests/admin/test_monitoring_location.py
Title
-----------
Added tests for /registry/admin/registry/monitoringlocation/add/ and change
Description
-----------
* Tests for the registry/admin/monitoringlocation/add/, GET method, for superusers and non-USGS users returns a 200.
* Tests for the registry/admin/monitorinlocation/<id>/change/, GET method, for a superuser, for a USGS user and for a non-USGS user.
=> added tests for add and change

buildJenkinsfile, deployJenkinsfile
Title
-----------
Description
-----------
point the ecs_pipeline to last stable version (2.2.2) and not experimental master version
=> point ecs pipeline to version 2.2.2

wellregistry/registry/admin/monitoring_location.py
- [x ] Make sure all tests run
- [x ] Update the changelog appropriately
Title
-----------
Add wording to the Well Registry Management System
Description
-----------
If users change information in the Well Registry, it often does not show up on the map or user interface until the next day.  We would like to include verbiage that indicates that changes made in the Well Registry may not be visible until the next day.
=> fixed message note on monitoring location

wellregistry/wellregistry/settings.py
Title
-----------
Description
-----------
=> Try to use USE_X_FORWARED_HOST to fix production url redirect issue.

CHANGELOG.md, wellregistry/registry/tests/admin/test_auto_complete.py, wellregistry/registry/tests/admin/test_bulk_upload.py, wellregistry/registry/tests/admin/test_fetch_from_nwis.py, wellregistry/registry/tests/admin/test_monitoring_location.py, wellregistry/registry/tests/test_views.py, wellregistry/wellregistry/settings.py, wellregistry/wellregistry/urls.py
=> Change the app root from registry to location-registry

wellregistry/wellregistry/settings.py
Title
-----------
Description
-----------
=> Set USE_X_FORWARDED_HOST to false

CHANGELOG.md, pipeline.yml, wellregistry/registry/tests/admin/test_auto_complete.py, wellregistry/registry/tests/admin/test_bulk_upload.py, wellregistry/registry/tests/admin/test_fetch_from_nwis.py, wellregistry/registry/tests/admin/test_monitoring_location.py, wellregistry/registry/tests/test_views.py, wellregistry/wellregistry/settings.py, wellregistry/wellregistry/urls.py
Title
-----------
Description
-----------
=> Repoint app

wellregistry/wellregistry/settings.py
Title
-----------
Description
-----------
=> Update static url

buildJenkinsfile, deployJenkinsfile, pipeline.yml
Title
-----------
https://internal.cida.usgs.gov/jira/browse/IOW-786
Description
-----------
=> tagging updates

CHANGELOG.md, wellregistry/registry/admin/bulk_upload.py, wellregistry/registry/models.py, wellregistry/registry/tests/test_models.py, wellregistry/wellregistry/static/css/admin.css, wellregistry/wellregistry/templates/admin/bulk_upload.html
Title
-----------
Add validation to well depth field in well registry
Description
-----------
The lack of validation in the well depth field is blocking bulk uploads from succeeding. We need to add validation to the well depth field in the well registry so that:
1) Users can upload sites with null values in the well depth field
2) We catch not valid numbers (such as 1..1)
Please see NGWMN-2090 outlining why this ticket was created. 
=> Validation for decimals in bulk upload

CHANGELOG.md, README.md, code.json, start_ci_db.bash, wellregistry/registry/admin/__init__.py, wellregistry/registry/admin/fetch_from_nwis.py, wellregistry/registry/models.py, wellregistry/registry/views.py, wellregistry/wellregistry/__init__.py, wellregistry/wellregistry/templates/admin/base_site.html, wellregistry/wellregistry/templates/admin/bulk_upload.html, wellregistry/wellregistry/templates/base.html, wellregistry/wellregistry/templates/registration/login.html, wellregistry/wellregistry/templates/registry/index.html
NGWMN-2105
Rename Well Registry to Monitoring Locations Registry
I did not change the app directory or DJango project structure.
=> NGWMN-2105 Rename Well Registry to Monitoring Locations Registry

CHANGELOG.md, wellregistry/wellregistry/templates/admin/bulk_upload.html
Title
-----------
NGWMN-2105 is a rebranding from Well Registry to Monitoring Location Registry.
Description
-----------
This merge updates and corrects the ChangeLog and fixes on minor plural in the UI.
=> NGMWN-2105 fix changelog and plural on upload
